version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - AWS_ACCESS_KEY_ID=myfakekey
      - AWS_SECRET_ACCESS_KEY=myfakesecret
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
