version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - AWS_ACCESS_KEY_ID=AKIASFEFGCHVIWFT5YLB
      - AWS_SECRET_ACCESS_KEY=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
      

  # nginx:
  #   build: ./docker/nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - django
