version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      - AWS_ACCESS_KEY_ID=AKIASFEFGCHVIWFT5YLB
      - AWS_SECRET_ACCESS_KEY=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
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
