# Generated by Django 3.0.7 on 2020-07-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StormTrooper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TK-421', max_length=100)),
                ('location', models.CharField(default='Death Star', max_length=200)),
                ('height', models.CharField(choices=[('short', 'Short'), ('tall', 'Tall')], max_length=20)),
            ],
        ),
    ]
