# Generated by Django 3.0.7 on 2020-07-30 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='username',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
