# Generated by Django 3.0.7 on 2020-07-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
