# Generated by Django 3.0.7 on 2020-07-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0002_auto_20200723_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
