# Generated by Django 3.0.7 on 2020-07-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0003_auto_20200730_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='photo_id',
        ),
    ]
