# Generated by Django 3.0.7 on 2020-07-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0003_customuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
    ]
