# Generated by Django 3.0.7 on 2020-07-30 23:22

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('photoreview', '0004_auto_20200730_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedphoto',
            name='slug',
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='#add #some #hashtags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
