# Generated by Django 3.0.7 on 2020-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0005_uploadedphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
