# Generated by Django 3.0.7 on 2020-07-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0006_auto_20200727_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='apps/photoreview/default.jpeg', upload_to=''),
        ),
    ]
