# Generated by Django 3.0.7 on 2020-07-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0006_auto_20200731_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='tags',
            field=models.ManyToManyField(to='photoreview.Tag'),
        ),
        migrations.AlterField(
            model_name='uploadedphoto',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
