# Generated by Django 3.0.7 on 2020-07-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoreview', '0010_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='apps/photoreview/default.jpeg', null=True, upload_to=''),
        ),
    ]
